.TH "nydus-server" "1" "Jan 2025" "Christopher Irving" ""
.SH "NAME"
.LP 
nydus\-server \- Nydus Launcher server program which authenticates Minecraft accounts and allocates them to clients. 
.SH "SYNTAX"
.LP 
nydus\-server
.SH "DESCRIPTION"
.LP 
Nydus Launcher server program which authenticates Minecraft accounts and allocates them to clients. 
