.TH "nydus-client" "1" "Jan 2025" "Christopher Irving" ""
.SH "NAME"
.LP 
nydus\-client \- Client program which requests a Minecraft account from the Nydus Launcher server and launchers Minecraft with it. 
.SH "SYNTAX"
.LP 
nydus\-client
.SH "DESCRIPTION"
.LP 
Client program which requests a Minecraft account from the Nydus Launcher server and launchers Minecraft with it.
